version: "3.3"

services:
# http://localhost/index.php/admin/authentication/sa/login
  app:
    image: acspri/limesurvey:5.2.11.1
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      LIMESURVEY_DB_HOST: ${LIMESURVEY_DB_HOST:-mysql}
      LIMESURVEY_TABLE_PREFIX: ${LIMESURVEY_TABLE_PREFIX}
      LIMESURVEY_DB_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-e/xa|m|ple}
      LIMESURVEY_ADMIN_USER: ${LIMESURVEY_ADMIN_USER:-admin}
      LIMESURVEY_ADMIN_PASSWORD: ${LIMESURVEY_ADMIN_PASSWORD:-password}
      LIMESURVEY_ADMIN_NAME: ${LIMESURVEY_ADMIN_NAME:-Lime Administrator}
      LIMESURVEY_ADMIN_EMAIL: ${LIMESURVEY_ADMIN_EMAIL:-lime@lime.lime}
      LIMESURVEY_DEBUG: ${LIMESURVEY_DEBUG:-0} # 2
      LIMESURVEY_SQL_DEBUG: ${LIMESURVEY_SQL_DEBUG:-0} #1, with 2 above
      LIMESURVEY_USE_INNODB: ${LIMESURVEY_USE_INNODB:-Y}
      APACHE_RUN_USER: ${APACHE_RUN_USER:-default_user}
      APACHE_RUN_GROUP: ${APACHE_RUN_GROUP:-root}
    volumes:
      - app_plugins:/var/www/html/plugins:delegated
      - app_upload:/var/www/html/upload:delegated
      - app_config:/var/www/html/application/config:delegated

  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-e/xa|m|ple}
      LIMESURVEY_DB_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-e/xa|m|ple}
      LIMESURVEY_ADMIN_USER: ${LIMESURVEY_ADMIN_USER:-admin}
      LIMESURVEY_ADMIN_PASSWORD: ${LIMESURVEY_ADMIN_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/mysql:delegated

volumes:
  app_plugins:
  app_upload:
  app_config:
  db_data:     