version: "3.3"

services:
  app:
    image: acspri/limesurvey
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/plugins:/var/www/html/plugins
      - ${WEBAPP_STORAGE_HOME}/site/upload:/var/www/html/upload
    environment:
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
      MYSQL_SSL_CA: BaltimoreCyberTrustroot.crt.pem
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: TRUE
      LIMESURVEY_USE_INNODB: 1
      LIMESURVEY_DB_NAME: limesurvey1
      LIMESURVEY_DB_USER: adminuser@adamtestlimesurvey
      LIMESURVEY_DB_PASSWORD: crazypassword1!
      LIMESURVEY_DB_HOST: adamtestlimesurvey.mysql.database.azure.com
    restart: always
